### ISSUE TITLE
User Story - Display Movies

### ISSUE THREAD

**Issue by rachelbuchta** [rachelbuchta/rancidTomatillos#1]
**User Story**
As a user, when I visit the app, all movies should be displayed.

**Details**
When the user first loads the page is when all of the movies should load in a grid format.
The user should also potentially see a loading screen when the movie data is being fetched from API. 

**Acceptance Criteria**
We will know this is successful when on page load the loading screen is briefly glimpsed followed by all movies loading on-screen in a grid format.

**Tasks**
- [x] Create file structure with associates folders
- [x] Import Data file from provided gist
- [x] Get all movies to display
- [x] NPM install sass
- [x] basic scss styling
