### ISSUE TITLE
Dev - Improve Page Styling

### ISSUE THREAD

**Issue by colefiscus** [rachelbuchta/rancidTomatillos#10]
**Tasks**
- [x]  Pick a font
- [x] Get movie detail card looking good 
- [x] Add line breaks in movie details card
- [ ] Tighten up Scss
