### ISSUE TITLE
Dev - Refactor

### ISSUE THREAD

**Issue by colefiscus** [rachelbuchta/rancidTomatillos#12]
**Tasks**
- [x] Refactor code to display API data instead of model data
- [ ] DRY up API call function?
- [ ] Utilize mixins and variables for scss?
