### ISSUE TITLE
Dev - Set-Up

### ISSUE THREAD

**Issue by rachelbuchta** [rachelbuchta/rancidTomatillos#2]
**Tasks**
- [x] Project Board Started
- [x] Make PR Template
- [x] Make Wireframes
- [x] Make initial place
- [x] Send day 1 deliverables
