### ISSUE TITLE
User Story - Movie Details

### ISSUE THREAD

**Issue by rachelbuchta** [rachelbuchta/rancidTomatillos#4]
**User Story**
As a user, when I click on a specific movie, I can see that movie's details.

**Details**
On the load screen, all movies will be organized in a grid format.
When a user clicks on one movie, the screen should change to show only the movie's details, the header, and the footer - all of the other movies should disappear from view. The movie details should include the title, the average rating, the release date, the poster, and the background image should be the movie's backdrop picture.

**Acceptance Criteria**
We will have success when a user can click on any single movie from the movie grid so that they only see the movies details plus the header and footer, and all other movie cards are removed from view.

**Tasks**
- [x] Create a function that handles an onClick event
- [x] Create a movie details component
- [x] Pass handleClick method as props and use with event listener on poster.
- [x] When a user clicks, the details appear and all the other movies disappear
