### ISSUE TITLE
Dev - Fetch API Data

### ISSUE THREAD

**Issue by rachelbuchta** [rachelbuchta/rancidTomatillos#6]
**Tasks**
- [x] create a file in src for all API calls
- [x] Create API call functions
- [x] Use the API call functions in componentDIdMount method in App
- [x] Assign that data to state so that it takes place of our dummy data
- [x] Pass down API data as props to display on page
